"""Export the current edited map-art.blend without rebuilding its geometry."""
import bpy, json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[2]
hidden = {c.name:c.hide_viewport for c in bpy.context.scene.collection.children}
for c in bpy.context.scene.collection.children: c.hide_viewport=False
bpy.context.view_layer.update()
# Triangulate evaluated meshes, deduplicate exported corners including normals/colors.
# The library stays component-editable; export does not apply destructive modifiers.
assets={}; stats={}
for coll in bpy.context.scene.collection.children:
    if not coll.objects: continue
    positions=[]; normals=[]; colors=[]; indices=[]; lookup={}
    for o in coll.objects:
        if o.type!='MESH': continue
        ev=o.evaluated_get(bpy.context.evaluated_depsgraph_get()); m=ev.to_mesh(); m.calc_loop_triangles()
        normal_matrix=o.matrix_world.to_3x3().inverted().transposed()
        for tri in m.loop_triangles:
            mat=m.materials[tri.material_index]; rgb=mat.diffuse_color[:3]
            for li in tri.loops:
                loop=m.loops[li]; p=o.matrix_world @ m.vertices[loop.vertex_index].co
                no=normal_matrix @ m.corner_normals[li].vector; no.normalize()
                vals=tuple(round(float(v),4) for v in (p.x,p.z,-p.y,no.x,no.z,-no.y,*rgb))
                if vals not in lookup:
                    lookup[vals]=len(positions)//3; positions.extend(vals[:3]); normals.extend(vals[3:6]); colors.extend(vals[6:])
                indices.append(lookup[vals])
        ev.to_mesh_clear()
    assets[coll.name]={'p':positions,'n':normals,'c':colors,'i':indices}
    stats[coll.name]={'vertices':len(positions)//3,'triangles':len(indices)//3}
OUT=ROOT/'assets/models'
OUT.mkdir(parents=True,exist_ok=True)
(OUT/'map-art.js').write_text('// Generated by tools/blender/build_map_art.py. Do not edit.\nexport default '+json.dumps(assets,separators=(',',':'))+';\n')
(OUT/'map-art-manifest.json').write_text(json.dumps({'generator':'Blender '+bpy.app.version_string,'assets':stats},indent=2)+'\n')
for c in bpy.context.scene.collection.children: c.hide_viewport=hidden[c.name]
print('NERF_ART_EXPORT',json.dumps(stats))
