// Optional browser regression; see docs/vr-validation.md.
import {createRequire} from 'node:module';
import {dirname,resolve} from 'node:path';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const require=createRequire(import.meta.url);
const iwerBundle=process.env.IWER_BUNDLE || resolve(dirname(require.resolve('iwer')),'../build/iwer.js');
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,channel:'chrome',args:['--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader']});
try {
const context=await browser.newContext({viewport:{width:1000,height:800},ignoreHTTPSErrors:true});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message)});
await page.addInitScript({content:readFileSync(iwerBundle,'utf8')+`\nwindow.xrDevice=new IWER.XRDevice({...IWER.oculusQuest1,userAgent:navigator.userAgent},{stereoEnabled:true});xrDevice.installRuntime({forceInstall:true});xrDevice.position.set(0,1.6,0);const request=navigator.xr.requestSession.bind(navigator.xr);navigator.xr.requestSession=async(...args)=>window.xrTestSession=await request(...args);`});
await page.goto(new URL('?quality=low',process.env.NERF_TEST_URL || 'http://localhost:3000').href,{waitUntil:'domcontentloaded'});
await page.waitForFunction(()=>window.__game?.()?.player&&document.getElementById('maploading').hidden,{timeout:120000});
await page.evaluate(()=>document.exitPointerLock?.());
await page.waitForFunction(()=>getComputedStyle(document.querySelector('#vr-entry')).display!=='none');
await page.locator('#vr-entry button').click();
await page.waitForFunction(()=>__game().player.vrActive,{timeout:15000});
await page.waitForTimeout(200);assert.equal(await page.locator('#vr-entry').isVisible(),false);
const button=async(hand,id,value)=>{await page.evaluate(({hand,id,value})=>xrDevice.controllers[hand].updateButtonValue(id,value),{hand,id,value});await page.waitForTimeout(120);};
const press=async(hand,id)=>{await button(hand,id,1);await button(hand,id,0);};
const atlas=async(name)=>{const data=await page.evaluate(name=>__vr().ui[name].canvas.toDataURL(),name);writeFileSync(`/tmp/nerf-vr-${name}.png`,Buffer.from(data.split(',')[1],'base64'));};
const clickMenu=async(id,confirmButton='trigger')=>{
 await page.evaluate(async id=>{
  const T=await import('three');const v=__vr(), ui=v.ui, b=ui.buttons.find(b=>b.id===id);
  ui.menu.mesh.updateWorldMatrix(true,false);
  const target=new T.Vector3(((b.x+b.w/2)/1024-.5)*1.38,(.5-(b.y+b.h/2)/1120)*1.51,0);
  ui.menu.mesh.localToWorld(target);v.rig.worldToLocal(target);
  const controller=xrDevice.controllers.right;
  const origin=new T.Vector3(controller.position.x,controller.position.y,controller.position.z);
  const q=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,0,-1),target.sub(origin).normalize());
  controller.quaternion.set(q.x,q.y,q.z,q.w);
 },id);
 await page.waitForTimeout(200);
 assert.equal(await page.evaluate(()=>{const u=__vr().ui;return u.buttons[u.hovered]?.id}),id);
 await press('right',confirmButton);
};
await press('right','b-button');
assert.equal(await page.evaluate(()=>__vr().active&&__vr().paused&&__game().paused),true);
assert.equal(await page.locator('#vr-entry').isVisible(),false);
await atlas('menu');
await clickMenu('resume');assert.equal(await page.evaluate(()=>__vr().paused),false);
console.log('B pauses without exiting; ray-selected resume works');
await page.evaluate(()=>{window.__start('canopy');});
await page.waitForFunction(()=>__game()?.mapDef?.id==='canopy'&&document.getElementById('maploading').hidden&&__game().player.vrActive,{timeout:120000});
await page.evaluate(()=>{const p=__game().player;p.grapple=true;p.hp=20;p.shield=35;p.weapons.scatter=true;p.ammo.scatter=2;p.switchWeapon('scatter');xrDevice.controllers.right.quaternion.set(0,0,0,1);xrDevice.controllers.left.quaternion.set(Math.sin(.3),0,0,Math.cos(.3));});
await page.waitForTimeout(200);
await atlas('vitals');
await press('right','b-button');const pausedTime=await page.evaluate(()=>__game().timeLeft);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>__game().timeLeft),pausedTime);await page.evaluate(()=>{__vr().ui.selected=1;});await clickMenu('resume','a-button');await page.waitForTimeout(150);
const aim=await page.evaluate(()=>({gun:__game().player.xrAim.dir.toArray(),grapple:__game().player.xrGrappleAim.dir.toArray(),leftVisible:__vr().grappleGun.visible,leftParent:__vr().grappleGun.parent.userData.source.handedness}));
assert.equal(aim.leftParent,'left');assert.equal(aim.leftVisible,true);assert.notDeepEqual(aim.gun,aim.grapple);
// Put a known grapple target on the left-hand ray, independently of the gun ray.
await page.evaluate(()=>{const p=__game().player,a=p.xrGrappleAim;__game().world.grappleFoliageTargets.push({center:a.origin.clone().addScaledVector(a.dir,12),radius:2});});
await button('left','trigger',1);assert.equal(await page.evaluate(()=>__game().player.grappleAttached),true);
await button('right','trigger',1);
assert.equal(await page.evaluate(()=>__game().player.grappleAttached&&__game().player.firing),true);
await button('left','trigger',0);await button('right','trigger',0);
await press('left','trigger');assert.equal(await page.evaluate(()=>__game().player.grappleAttached),false);
await page.evaluate(()=>__vr().award('LONG SHOT','125 metres · +250','#ffd23c'));await page.waitForTimeout(100);
assert.equal(await page.evaluate(()=>__vr().ui.awards.mesh.visible),true);await atlas('awards');
await page.screenshot({path:'/tmp/nerf-vr-hands-stereo.png'});
await page.waitForTimeout(2600);assert.equal(await page.evaluate(()=>__vr().ui.awards.mesh.visible),false);
console.log('independent left grapple, simultaneous shooting, colored vitals, awards passed');
await page.evaluate(()=>{const p=__game().player;p.hp=100;p.score=2400;p.kills=8;__game().timeLeft=0;});
await page.waitForFunction(()=>__game()?.scene?.userData?.end&&__vr().podium,{timeout:15000});
await page.waitForTimeout(500);
const podium=await page.evaluate(async()=>{const T=await import('three'),v=__vr();return {distance:v.camera.getWorldPosition(new T.Vector3()).distanceTo(v.podium.lookAt),visible:v.ui.menu.mesh.visible,result:v.ui.menu.key};});
assert.ok(podium.distance<20);assert.equal(podium.visible,true);assert.match(podium.result,/2400/);
assert.deepEqual(await page.evaluate(()=>__vr().ui.buttons.map(b=>b.id)),['atrium']);
await press('right','b-button');assert.equal(await page.evaluate(()=>__vr().active&&__game().over),true);await press('right','b-button');
await atlas('menu');await page.screenshot({path:'/tmp/nerf-vr-podium-stereo.png'});
await page.evaluate(()=>xrDevice.quaternion.set(0,Math.sin(-.255),0,Math.cos(-.255)));
await page.waitForTimeout(200);
await page.screenshot({path:'/tmp/nerf-vr-results-stereo.png'});
await clickMenu('atrium');
await page.waitForFunction(()=>__game()?.atrium&&document.getElementById('maploading').hidden&&__game().player.vrActive,{timeout:120000});
await page.evaluate(()=>xrDevice.quaternion.set(0,0,0,1));await page.waitForTimeout(200);
assert.equal(await page.evaluate(()=>__vr().active),true);console.log('podium visible; scores and ray-selected Atrium work without leaving VR');
await press('right','b-button');assert.equal(await page.evaluate(()=>__vr().active),true);
assert.equal(await page.evaluate(()=>__vr().ui.buttons.some(b=>b.id==='exit')),false);
await page.evaluate(()=>window.xrTestSession.end());
await page.waitForFunction(()=>!__vr().active,{timeout:15000});
assert.deepEqual(errors,[]);console.log('PASS');
}finally{await browser.close();}
